-- Supabase schema for Soportes EPS.
-- Run this once in Supabase SQL Editor before enabling the .env connection.

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  local_id integer,
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('Administrador', 'Digitador', 'Consulta')),
  active integer not null default 1,
  created_at text not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.eps (
  id bigint generated by default as identity primary key,
  local_id integer,
  name text not null unique,
  nit text,
  code text,
  color text not null default '#1769e0',
  logo_url text,
  aliases text,
  active integer not null default 1,
  created_at text not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.supports (
  id bigint generated by default as identity primary key,
  local_id integer,
  original_filename text not null,
  stored_filename text not null,
  path text not null,
  storage_path text,
  eps_id integer,
  eps_name text,
  radication_date text,
  radicado text,
  factura text,
  corte text,
  invoice_count integer not null default 0,
  invoice_numbers text,
  nit_eps text,
  valor_radicado text,
  year integer,
  month integer,
  uploaded_at text not null,
  uploaded_by integer,
  uploaded_by_name text not null,
  size_bytes bigint not null default 0,
  sha256 text not null unique,
  status text not null,
  observations text,
  extracted_text text,
  synced_at timestamptz not null default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  local_id integer,
  fingerprint text not null unique,
  user_id integer,
  user_name text,
  action text not null,
  entity_type text not null,
  entity_id integer,
  details text,
  ip_address text,
  created_at text not null,
  synced_at timestamptz not null default now()
);

create table if not exists public.settings (
  key text primary key,
  value text not null,
  synced_at timestamptz not null default now()
);

create index if not exists idx_supports_filters
  on public.supports (eps_name, year, month, radication_date, radicado, factura, status);
create index if not exists idx_supports_corte
  on public.supports (year, month, corte);
create index if not exists idx_audit_logs_created_at
  on public.audit_logs (created_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('soportes-eps', 'soportes-eps', false, 26214400, array['application/pdf'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

alter table public.app_users enable row level security;
alter table public.eps enable row level security;
alter table public.supports enable row level security;
alter table public.audit_logs enable row level security;
alter table public.settings enable row level security;

revoke all on table public.app_users from anon, authenticated;
revoke all on table public.eps from anon, authenticated;
revoke all on table public.supports from anon, authenticated;
revoke all on table public.audit_logs from anon, authenticated;
revoke all on table public.settings from anon, authenticated;

grant usage on schema public to service_role;
grant select, insert, update, delete on table public.app_users to service_role;
grant select, insert, update, delete on table public.eps to service_role;
grant select, insert, update, delete on table public.supports to service_role;
grant select, insert, update, delete on table public.audit_logs to service_role;
grant select, insert, update, delete on table public.settings to service_role;
grant usage, select on all sequences in schema public to service_role;
